/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    CompanyItem: typeof import('./src/components/CompanyItem.vue')['default']
    Companytem: typeof import('./src/components/Companytem.vue')['default']
    copy: typeof import('./src/components/CV copy.vue')['default']
    CV: typeof import('./src/components/CV.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon3Commas: typeof import('./src/components/icons/Icon3Commas.vue')['default']
    IconClodo: typeof import('./src/components/icons/IconClodo.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconGmail: typeof import('./src/components/icons/IconGmail.vue')['default']
    IconInCountry: typeof import('./src/components/icons/IconInCountry.vue')['default']
    IconIqOption: typeof import('./src/components/icons/IconIqOption.vue')['default']
    IconLinkedIn: typeof import('./src/components/icons/IconLinkedIn.vue')['default']
    IconPropellerAds: typeof import('./src/components/icons/IconPropellerAds.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTelegram: typeof import('./src/components/icons/IconTelegram.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    WrapperHeader: typeof import('./src/components/WrapperHeader.vue')['default']
  }
}
